
<div id="divCreate">
  <?php $form->setAttribute('onsubmit', 'return false');
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
  ?>
  <Span id="lblName">Category Name</Span>
  <input type="text" class="form-control margin-left50" name="txtCategoryName" id="txtCategoryName" maxlength="30" placeholder="max 30 characters"/>
  
  <p></p>
  <div id="errCat" class="margin-left50"></div>
  <input type="button" value="Add Category"  class="btn margin-left50 margin-top10" id="btnAddCategory"/>
  <p></p>

</div>
<script>

$(document).ready(function(){
  $("#txtCategoryName").on("keypress", function(e) {
  if (e.which === 32 && !this.value.length)
      e.preventDefault();
  });
});
</script>

<!-- 
<div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Add New Category</h4>
      </div>
      <?php
      //$form->setAttribute('action', $this->url('category', array('action' => 'add')));
       // $form->prepare();

       //echo $this->form()->openTag($form); ?>

      <div class="modal-body" >
        <?php

        
        //echo $this->formHidden($form->get('id'));
        //echo $this->formRow($form->get('name'));

       
        

         ?>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <input type="button" id="addbtn" class="btn btn-primary" name = "submit" value = "Add">
      </div>
      <?php //echo $this->form()->closeTag(); ?>
    </div>
  </div>  -->