<?php $form = $this->form;?>
<?php $form->prepare();?>
<div class="modal fade" id="myModal">
	<div class="modal-dialog">
    	<div class="modal-content">
    		<?php echo $this->form()->openTag($form);?>
    		<?php echo $this->formHidden($form->get('id'));?>
    			<div class="modal-header">
        			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        			<h4 class="modal-title">Add new category </h4>
      			</div>
      			<div class="modal-body form-horizontal">
      				<div class="form-group">
      					<?php echo $this->formLabel($form->get('name'));?>
		    			<div class="col-sm-8">
							<?php echo $this->formElement($form->get('name'));?>    		    			
						</div> 
					</div>
      			</div>
      			<div class="modal-footer">
        			<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        			<?php echo $this->formElement($form->get('submit-category'));?>
        		</div>
			<?php echo $this->form()->closeTag($form);?>
		</div>
  </div>
</div>