<div id="divCreate">
  <Span id="lblName">Are you sure want to delete?</Span>
  <Span id="warningMsg"><h6 style="margin-left:50px">All the questions of this Category will also be deleted</h6></Span>
  <input type="text" class="form-control margin-left50" value="<?php echo $_GET['catname'];?>" disabled="disabled" name="txtCategoryDel"/>
  <p></p>
  <div id="errDeleteCat" class="margin-left50"></div>
  <button type="button" id="deleteCategory" class="btn btn-primary margin-left50 margin-top10"  value="<?php echo $_GET['catid'];?>">Confirm</button>

  <p></p>
</div>

<!-- 
<div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        <h4>Do you want to delete this Category </h4>
      </div>


      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" name="del" value="No">Cancel</button>
        <button type="button" id="deleteCategory" class="btn btn-primary"  value="<?php //echo $_GET['catid'];?>">Delete</button>
      </div>

    </div>
  </div> -->