<div id="divCreate">
<br/>
  <Span id="lblName">Are you sure want to delete?</Span>
  <Span id="warningMsg"><h6 style="margin-left:50px">All the questions of these Categories will also be deleted</h6></Span>
  <br/>
  <p></p>
    <br/>
  <input type="button" value="Confirm" class="btn margin-left50 margin-top10" id="btnMulDelCat" onclick="deleting();"/>
  <p></p>
    <div id="errCatMsg" class="margin-left50"></div>
</div>




<!-- <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        <h4>Do you want to delete all these Categories </h4>
      </div>


      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" name="del" value="No">Cancel</button>
        <button type="button" id="delmulcat" class="btn btn-primary"  onclick="deleting();">Delete</button>
      </div>

    </div>
  </div> -->