<?php 
$title = 'Category';
$this->headTitle($title);
$pageCount = $rowCount / $defaultSelect;
?>
<input type="hidden" value='<?php echo $rowCount;?>' id="row-count">
<div class="row">
	<div class="col-sm-4 form-horizontal">
		<div class="form-group">
			<label class="control-label col-sm-2" for="tbl-select-value">
    			Show
    		</label>
    		<div class="col-sm-4">
    			<select name="tbl-select-value" id="tbl-select-value" class="form-control input-sm">
					<option value="1">1</option>
					<option value="2">2</option>
					<option value="3">3</option>
					<option value="8">8</option>
				</select> 
    		</div>
    		<label class="control-label col-sm-2" for="tbl-select-value">
    			entries
    		</label>
  		</div>
  	</div>
	<div class="col-sm-4">
		<button id="create-category" type="button" class="btn btn-primary col-sm-offset-3">
			+New category
		</button>
	</div>
		<div class="col-sm-4 form-horizontal">
			<div class="form-group">
				<label class="control-label col-sm-3" for="tbl-select-value">
    				Search:
    			</label>
    			<div class="col-sm-9">	
					<input type="search" class="form-control input-sm">
				</div>
			</div>
	</div>
</div>
<div class="row">
	<div class="col-sm-12">
        <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
        	<thead>
        		<tr>
        			<th><input type="checkbox" id="chkAll" /></th>
                    <th>Category</th>
                    <th class="action">Actions</th>
               </tr>
        	</thead>
        	<tbody>
        	<?php foreach ($categories as $category):?>
        		<tr>
        			<td>
        				<input type="checkbox" value="<?php echo $this->escapehtml($category['id']);?>" 
        				name="deleteall" id="newchk" >
        			</td>
        			<td>
        			   	<a title='Select the category to add questions' href='<?php echo $category['id'];?>' 
        			   		class="viewQuestion" id="<?php echo $category['id'];?>">
        			   		<?php  echo $this->escapehtml($category['name']);?>
        			   	</a>
        			</td>
        			<td>
        				<a class="col-sm-3" onclick="deleteCategory(this, '<?php echo $category['id']?>')" style="cursor:pointer;">
        					<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
        				</a>
                    	<a class="col-sm-3" href="/category/2" style="cursor:pointer;">
                    		<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                    	</a>
                    	<a class="col-sm-3" href="/category/3" style="cursor:pointer;">
                    		<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                    	</a>
                    </td>
        		</tr>
        	<?php endforeach;?>
        	</tbody>
        </table>
    </div>
</div>
<div class="row">
		<div class="dataTables_info" id="example_info" role="status" aria-live="polite">
			Showing 1 to 1 of 1 entries
		</div>
</div>
<div class="row">
	<div class="col-md-offset-5">
		<nav id="tbl-pagination">
			<ul class="pagination">
    			<li class="disabled">
      				<a href="#" aria-label="Previous">
        				<span aria-hidden="true">&laquo;</span>
      				</a>
    			</li>
    			<?php for ($i=$pageCount; $i--; $i >=0) :?>
    				<?php $page = $pageCount - $i;?>
    				<li <?php if($selectedPage == $page): echo 'class="active"';endif;?>>
    					<a href="#"><?php echo $page;?></a>
    				</li>
    			<?php endfor;?>
    			<li class="disabled">
      				<a href="#" aria-label="Next">
        				<span aria-hidden="true">&raquo;</span>
      				</a>
    			</li>
  			</ul>
		</nav>
	</div>
</div>