<?php 

?>


<div class="Quesdetails-left">Type :<strong> Multiple <?php  ?></strong><br>

 Created By : <strong><?php echo $this->escapehtml($categories->created_by);?></strong><br>
 Created on : <strong><?php echo $this->escapehtml($categories->created_on);?></strong><br>
                                                          
  </div>
  
  <div class="Quesdetails-right margin-top0 ">Status :<strong> Active</strong><br>
 Updated By : <strong><?php echo $this->escapehtml($categories->updated_by);?></strong><br>
 Updated On : <strong><?php echo $this->escapehtml($categories->updated_on);?></strong><br>
                                                              
   </div>