<div class="col-md-8 col-md-offset-2">
  <ul class="list-group">
    <li class="list-group-item">
    	<label>Category Name  :</label> <?php echo $this->escapehtml($rowCategory['name']);?>
    </li>
    <li class="list-group-item">
    	<label>Created By : </label> <?php echo $this->escapehtml($rowCategory['createdBy']);?>
    </li>
    <li class="list-group-item">
    	<label>Created on : </label><?php echo $this->escapehtml($rowCategory['created_on']);?></label>
    </li>
    <li class="list-group-item">
    	<label>Updated By : </label><?php echo $this->escapehtml($rowCategory['updatedBy']);?></label>
    </li>
    <li class="list-group-item">
    	<label>Updated On : </label><?php echo $this->escapehtml($rowCategory['updated_on']);?>
    </li>
  </ul>
</div>