<div class="row" id="content">
	<div class="col-md-2"></div>
	<div class="col-md-5">
		<form id="frm-forgot-password">
			<div class="form-group">
				<label for="txt-email">
					Please provide your registered Email:
		     	</label>
			 	<input type="text" class="form-control" id="txt-email" 
			 	name="txt-email" placeholder="Enter your E-mail"> 
		    </div>
			<div class="form-group">
				<button type="submit" class="btn btn-primary" id="forgot-password">Continue</button>
				<button type="button" class="btn btn-primary" id="goToLogin" style="display:none">OK</button>
			</div>
		</form>
	</div>
	<div class="clo-md-3">
		<img id="loadingImage" lass="img-responsive" src="<?php echo $this->basePath() . '/img/loading.gif'; ?>" 
		style="display:none">
	</div>
</div>
<script type="text/javascript">
$().ready(function () {
	$('#frm-forgot-password').validate({ // initialize the plugin
        rules: {
        	'txt-email':{
                required: true,
                email: true,
                maxlength :30
            }
        },
        submitHandler: function (form) {
            return false;
        }
    });
});
</script>