<div class="modal fade" id="myModal">
	<div class="modal-dialog">
    	<div class="modal-content">
    		<form id="frm-forgot-password">
    			<div class="modal-header">
        			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        			<h4 class="modal-title">Forgot Password</h4>
      			</div>
      			<div class="modal-body">
      				<div class="form-group">
      					<label for="txt-email">
      						Please provide your registered Email:
		    			</label>
						<input type="text" class="form-control" id="txt-email" 
							name="txt-email" placeholder="Enter your E-mail"> 
					</div>
      			</div>
      			<div class="modal-footer">
        			<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        			<button type="submit" class="btn btn-primary" id="forgot-password">Continue</button>
       			</div>
			</form>
		</div>
  </div>
</div>
<?php 
echo $this->inlineScript()->prependFile($this->basePath('/user/user.validation.js'));
?>