<?php
$form = $this->form;
$form->prepare();
$message = "";
$display = "display: none";
$class = "alert-danger";
if(isset($status) && $status == 1) : 
    $message = "Account Confirmed!";
    $display = "display: block";
    $class = "alert-success";
endif;
?>
<div id="popup-content" ></div>
<div class="container">
	<div id="loginbox" style="margin-top: 50px;"
		class="mainbox col-md-7 col-md-offset-2 col-sm-8 col-sm-offset-2">
		<div class="panel panel-info">
			<div class="panel-heading">
				<div class="panel-title">Sign In</div>
				<div style="float: right; font-size: 80%; position: relative; top: -10px">
					<a href="#" id="ancr-forgot-password">Forgot password?</a>
					<p></p>
				</div>
			</div>
			<div style="padding-top: 30px" class="panel-body">
				<div style="<?php echo $display;?>" id="login-alert" class="alert <?php echo $class;?> alert-dismissible fade in col-sm-12">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
  					<span aria-hidden="true">&times;</span>
				</button>
				<p><?php echo $message;?></p>
				</div>
				<?php echo $this->form()->openTag($form);?>
					<div style="margin-bottom: 25px" class="input-group">
						<span class="input-group-addon"> 
							<i class="glyphicon glyphicon-user"></i>
						</span> 
						<?php echo $this->formElement($form->get('username'));?>
					</div>
				<div style="margin-bottom: 25px" class="input-group">
					<span class="input-group-addon"> 
						<i class="glyphicon glyphicon-lock"></i>
					</span>
					<?php echo $this->formElement($form->get('password'));?> 
				</div>
				<div class="input-group">
					<div class="checkbox">
						<label> 
							<input id="login-remember" type="checkbox" name="remember" value="1">
								Remember me
							</label>
					</div>
				</div>
				<div style="margin-top: 10px" class="form-group">
					<!-- Button -->
					<div class="col-sm-12 controls">
							<?php echo $this->formElement($form->get('login-submit'));?>
							<a id="btn-fblogin" href="#" class="btn btn-primary">
								Login with Facebook
							</a>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-12 control">
						<div style="border-top: 1px solid #888; padding-top: 15px; font-size: 85%">
							Don't have an account! 
							<a href="#" id="ancr-register">
							 Sign Up Here 
							</a>
						</div>
					</div>
				</div>
				<?php echo $this->form()->closeTag($form);?>
				<?php 
//echo $this->inlineScript()->prependFile($this->basePath('/user/user.validation.js'));
?>
			</div>
		</div>
	</div>
</div>