<?php
$form = $this->form;
$form->prepare();
?>
<div class="container">
	<div id="signupbox" style="margin-top: 50px" 
		class="mainbox col-md-7 col-md-offset-2 col-sm-8 col-sm-offset-2">
		<div class="panel panel-info">
			<div class="panel-heading">
				<div class="panel-title">Sign Up</div>
				<div style="float: right; font-size: 85%; position: relative; top: -10px">
					<a id="signinlink" href="/">
						Sign In
					</a>
				</div>
			</div>
			<div class="panel-body">
				<?php echo $this->form()->openTag($form);?>
				<?php echo $this->formHidden($form->get('id'));?>
					<div id="signupalert" style="display: none" class="alert alert-danger">
						<p>Error:</p>
						<span></span>
					</div>
					<div class="form-group">
						<?php echo $this->formLabel($form->get('user-name'));?>
						<div class="col-md-9">
							<?php echo $this->formElement($form->get('user-name'));?>
						</div>
					</div>
					<div class="form-group">
						<?php echo $this->formLabel($form->get('first-name'));?>
						<div class="col-md-9">
							<?php echo $this->formElement($form->get('first-name'));?>	
						</div>
					</div>
					<div class="form-group">
						<?php echo $this->formLabel($form->get('last-name'));?>
						<div class="col-md-9">
							<?php echo $this->formElement($form->get('last-name'));?>			
						</div>
					</div>
					<div class="form-group">
						<?php echo $this->formLabel($form->get('email'));?>
						<div class="col-md-9">
							<?php echo $this->formElement($form->get('email'));?>
						</div>
					</div>
					<div class="form-group">
						<?php echo $this->formLabel($form->get('password'));?>
						<div class="col-md-9">
							<?php echo $this->formElement($form->get('password'));?>
						</div>
					</div>
					<div class="form-group">
						<?php echo $this->formLabel($form->get('confirm-password'));?>
						<div class="col-md-9">
							<?php echo $this->formElement($form->get('confirm-password'));?>
						</div>
					</div>
					<div class="form-group">						
						<?php echo $this->formLabel($form->get('captcha'));?>
						<a href="#" id="refreshbutton">Refresh Code</a>
						<div class="col-md-9">
							<?php echo $this->formElement($form->get('captcha'));?>								
						</div>
					</div>					
					<div class="form-group">
						<!-- Button -->
						<div class="col-md-offset-3 col-md-9">
							<?php echo $this->formElement($form->get('register-submit'));?>
							<span style="margin-left: 8px;">or</span>
						</div>
					</div>
					<div style="border-top: 1px solid #999; padding-top: 20px"
						class="form-group">
						<div class="col-md-offset-3 col-md-9">
							<button id="btn-fbsignup" type="button" class="btn btn-primary">
								<i class="icon-facebook"></i>   Sign Up with Facebook
							</button>
						</div>
					</div>
				<?php echo $this->form()->closeTag($form);?>
			</div>
		</div>
	</div>
</div>
<?php 
echo $this->inlineScript()->prependFile($this->basePath('/user/user.validation.js'));
?>