<?php 
//print_r($userdata);die;
//$image = new \Zend\View\Renderer\PhpRenderer();
if(isset($userProfile[0]) && !empty($userProfile[0])){ 
    $clientid = (isset($userProfile[0]['clientId']))?$userProfile[0]['clientId']:null;
    $email = (isset($userProfile[0]['email']))?$userProfile[0]['email']:null;
    $username = (isset($userProfile[0]['username']))?$userProfile[0]['username']:null;
    $registrationDate = (isset($userProfile[0]['regDate']))?$userProfile[0]['regDate']:null;
    //$lastlogin = $arrData['lastlogin'];
    $firstName = (isset($userProfile[0]['firstName']))?$userProfile[0]['firstName']:null;
    $lastName = (isset($userProfile[0]['lastName']))?$userProfile[0]['lastName']:null;
    //$mytheme = (isset($userProfile[0]['theme']))?$userProfile[0]['theme']:null;
    //$name = (isset($userProfile[0]['name']))?$userProfile[0]['name']:null;
    $contact = (isset($userProfile[0]['contact']))?$userProfile[0]['contact']:null;
    $photoPath = (isset($userProfile[0]['photo']))?$userProfile[0]['photo']:null;
    $language = (isset($userProfile[0]['lang']))?$userProfile[0]['lang']:null;
}
?>

<div id="profile_wrapper">
	<div id="left_pane">
		<div id="left_top">
			<div id="user-pic">
				<img class="profilePicSetting" id="profile-pic" 
					src="<?php echo "profilepics/".$photoPath; ?>"></img>
			</div>
        </div>
        <div id="left_bottom">
        	<div class="text-primary"">
        		<?php echo ucfirst($firstName)." ".ucfirst($lastName);?>
        	</div>
        	<div id="info">
        		<p></p>
        		<p>
        			Registration Date: 
					<span class="text-primary">
						<?php echo date_format(date_create($registrationDate), 'g:ia \o\n l  jS F Y'); ?>
					</span>
				</p>
				<p>
					Last Login: 
                	<span class="usrProfileSmallText">
                		<?php //echo $dated = date_format(date_create($last_login), 'g:ia \o\n l  jS F Y');?>
                	</span>
            	</p>
            	<p>
            		Account Type: 
            		<span class="text-primary">Admin</span>
            	</p>
           	</div>
        </div>
    </div>
    <div id="right_pane">
    	<div id="selectedTabBox"></div>
    	<div id="nav-tabs">
    		<ul class="nav nav-tabs" >
    			<li class="active"><a href="#home" data-toggle="tab" id="generaltab">General</a></li>
                <li><a href="#profile" data-toggle="tab" id="settingtab">Settings</a></li>
                <li><a href="#messages" data-toggle="tab" id="passtab">Change Password</a></li>
                <li><a href="#userlist" data-toggle="tab" id="usertab" >Users</a></li>
                <li><a href="#adduser" data-toggle="tab" id="addusertab" >Add new user</a></li>
            </ul>
            <!-- Tab panes -->
            <div class="tab-content">
            	<div class="tab-pane active" id="home">
            		<div id="generalContent">
            			<form id="update-profile" class="form-horizontal" enctype="multipart/form-data"  method="POST" >   
                            <input id="client-id" type="hidden" class="form-control" value="<?php echo $clientid;?>"/>
                            <div class="form-group">
                            	<label for="email" class="col-sm-2 control-label">Email</label>
                            	<div class="col-sm-10">
                            		<input type="text" class="form-control" id="email" value="<?php echo $email;?>" disabled="disable"/>
                            	</div>
                            </div>
                            <div class="form-group">
                            	<label for="username" class="col-sm-2 control-label">Username</label>
                            	<div class="col-sm-10">
                            		<input type="text" class="form-control" id="username" value="<?php echo $username;?>" disabled="disable" />
                            	</div>
                            </div>
                            <div class="form-group">
                            	<label for="firstName" class="col-sm-2 control-label">First Name</label>
                            	<div class="col-sm-10">
                             		<input type="text" name="firstName" id="first-name" class="form-control" value="<?php echo ucfirst($firstName); ?>" id="txtFname" required />
                             	</div>
                            </div>
                            <div class="form-group">
                            	<label for="lastName" class="col-sm-2 control-label">Last Name</label>
                             	<div class="col-sm-10">
                             		<input type="text" name="lastName" id="last-name" class="form-control"  value="<?php echo ucfirst($lastName); ?>" id="txtLname"/></p>
                             	</div>
                            </div>
                            <div class="form-group">
                            	<label for="contact" class="col-sm-2 control-label">Phone</label>
                            	<div class="col-sm-10">
                            		<input type="text" name="contact" id="contact" class="form-control" value="<?php if($contact) { echo $contact;} ?>" id="txtContact" max-length="10"/></p>
                            	</div>
                            </div>
                            <div class="form-group">
                            	<label for="image-upload" class="col-sm-2 control-label">Upload</label>
                            	<div class="col-sm-10">
                            		<span class="btn btn-primary btn-file">
    									Browse <input type="file" id="image-upload" name="profilePic">
									</span>
									<span id="file-name"><?php  echo $photoPath;?></span>
                            	</div>
                            </div>
                            <div class="form-group">
                            	<div class="col-sm-2"></div>
                                <div class="col-sm-10">
	                            	<input type="button" class="btn btn-primary"  value="Save" id="profile-save" />
	                            </div>
	                        </div>
                        </form> 
                    </div>
                </div>
            	<div class="tab-pane" id="profile">
            		<form class="form-horizontal">
            			<div class="form-group">
    						<label for="language" class="col-sm-2 control-label">
    							Language
    						</label>
    						<div class="col-sm-10">
            					<select id="language" class="form-control">
            						<option value="en">English</option>
            						<option value="fr">French</option>
            						<option value="hn">Hindi</option>
            					</select>
            				</div>
            			</div>
            			<div class="form-group">
    						<label for="" class="col-sm-2 control-label">
    							Theme
    						</label>
    						<div class="col-sm-10">
            					<input type="button" class="btn btn-primary theme" value="Blue" />
                				<input type="button" class="btn btn-success theme" value="Green" />
                				<input type="button" class="btn btn-warning theme"  value="Yellow" />
                				<input type="button" class="btn btn-danger theme"  value="Red" />
                				<input type="hidden" id="color" value="<?php echo $mytheme ?>">
                				<input type="hidden" id="client" value="<?php echo ($userProfile[0]['clientId']);  ?>">
                			</div>
                		</div>
                		<div class="form-group">
                			<div class="col-sm-offset-2 col-sm-10">
                				<input type="submit" class="btn proSave"  value="Save" id="btnThemeLang"/>
                			</div>
                		</div>
             		</form>
            	</div>
            	<div class="tab-pane" id="messages">
            		<h3>Set your new  Password here</h3>
            		<form class="form-horizontal" id="generalContent2">
            			<div class="form-group">
    						<label for="oldPassword" class="col-sm-3 control-label">
    							Password
    						</label>
    						<div class="col-sm-9">
            					<input type="password" class="form-control" id="oldPassword">
            				</div>
            			</div>
  						<div class="form-group">
  							<label for="newPassword" class="col-sm-3 control-label">
            					New Password 
            				</label>
            				<div class="col-sm-9">
            					<input type="password" class="form-control" id="newPassword" disabled = "disabled" >
            				</div>
            			</div>
            			<div class="form-group">
  							<label for="confirmPassword" class="col-sm-3 control-label">
  								Confirm Password
  							</label>
  							<div class="col-sm-9">
  								<input type="password" class="form-control" id="confirmPassword" disabled = "disabled">
            				</div>
            			</div>
            			<div class="form-group">
            				<div class="col-sm-offset-3 col-sm-9">
            					<input type="submit" class="btn btn-primary"  value="Save" id="btnSave" name="btnSave"/>            				
            				</div>
            			</div>
					</form>
				</div>
                <!-- users table-->
            	<div class="tab-pane" id="userlist">
					<div class="col-sm-12">
        				<table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
            				<thead>
            					<tr>
            						<th>S.No</th>
                    				<th>User Name</th>
                    				<th>Email Id</th>
                    				<th>Actions</th>
                    			</tr>
                    		</thead>
                			<tbody>
                				<?php $i=1;?>
                				<?php foreach ($userdata as $user): ?>
                		  		<tr>
                					<td><?php echo $i;?></td>
                    				<td><?php echo $this->escapehtml($user->username);?></a></td>
                    				<td><?php echo $this->escapehtml($user->email);?></a></td>
                    				<td>
        								<a class="col-sm-3" onclick="deleteCategory(this, '<?php echo $category['id']?>')" style="cursor:pointer;">
        									<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
        								</a>
                    					<a class="col-sm-3" onclick="createCategory('<?php echo $category['id']?>')" style="cursor:pointer;">
                    						<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                    					</a>
                    					<a class="col-sm-3" href="/category/viewCategory/<?php echo $category['id']?>" style="cursor:pointer;">
                    						<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                    					</a>
                    				</td>
               					</tr>
                 				<?php $i++; ?>
                            	<?php endforeach;?>    
            				</tbody>
            	    	</table>
            		</div>
            	</div>
            	<div class="tab-pane" id="adduser">
            		<h3>New user registeration</h3>
                	<div id="generalContent2">
                		<form class="form-horizontal">
  							<div class="form-group">
    							<label for="username" class="col-sm-3 control-label">
    								User Name
    							</label>
    							<div class="col-sm-9">
                					<input type="text" class="form-control" id="username">
                				</div>
                			</div>                     
                    		<div class="form-group">
    							<label for="first-name" class="col-sm-3 control-label">
    								First Name
    							</label>
    							<div class="col-sm-9">
                   					<input type="text" class="form-control" id="first-name">
                   				</div>
                   			</div>
                   			<div class="form-group">
    							<label for="last-name" class="col-sm-3 control-label">
    								Last Name
    							</label>
    							<div class="col-sm-9">
                    				<input type="text" class="form-control" id="last-name">
                    			</div>
                    		</div>
                    		<div class="form-group">
    							<label for="email" class="col-sm-3 control-label">
    								Email
    							</label>
    							<div class="col-sm-9">
    								<input type="Email" class="form-control" id="email">
    							</div>
    						</div>
                    		<div class="form-group">
    							<label for="password" class="col-sm-3 control-label">
    								Password
    							</label>
    							<div class="col-sm-9">
    								<input type="password" class="form-control" id="password">
                    			</div>
                    		</div>
                    		<div class="form-group">
    							<label for="retype-passwrd" class="col-sm-3 control-label">
    								Re-type password
    							</label>
    							<div class="col-sm-9">
    								<input type="text" class="form-control" id="retype-passwrd">
    							</div>
    						</div>
    						<div class="form-group">
    							<div class="col-sm-offset-3 col-sm-9">
    								<input type="submit" class="btn btn-primary"  value="Save" id="btnSave" name="btnSave"/>
    							</div>
    						</div>
    					</form>
               		</div>
		    	</div>
        	</div>
   		</div>
	</div>  
<script>
$(document).on('click', '#profile-save', function() {    
    var formData = new FormData();
    formData.append('file', $('#image-upload')[0].files[0]);
    var otherData = $('#update-profile').serializeArray();
    $.each(otherData, function(key, input){
        formData.append(input.name, input.value); 
    });

    $.ajax({
        url: '/user/generalProfileUpdate',
        type: 'POST',
        data:  formData,
        mimeType:"multipart/form-data",
        contentType: false,
        cache: false,
        processData:false,
        success: function(response, textStatus, xhr) {
            var ct = xhr.getResponseHeader('Content-Type') || "";
            if(ct.indexOf('json') > -1) {
            	response = JSON.parse(response)
            }
            console.log(response);
            if(response.flag == 1) {
            	$("#profile-pic").attr("src", response.profilePic);
            }
        }
    });
});
/*         $("#btnSave").click(function(){
           var oldPassword = $("#oldPassword").val();
           var newPassword = $("#newPassword").val();
           var confirmPassword = $("#confirmPassword").val()
           //alert(passValue);
           $.ajax({
            type: "POST",
            data: {oldPassword:oldPassword,newPassword:newPassword,confirmPassword:confirmPassword},
            url: base_url +'index.php?controller=dashboard&function=profilePassword', 
            dataType: 'json',
             beforeSend: function() {
                },
                success: function(response) {
                        if(response.passFlag == 1 ) {
                            $('#errPassMsg').html("Password cannot be blank").css("color","red");
                        } else if(response.passFlag == 2 ){
                            $('#errPassMsg').html("Password cannot be blank").css("color","red");
                        } else if(response.passFlag == 3 ){
                            $('#errPassMsg').html("Password cannot be blank").css("color","red");
                        } else if(response.passFlag == 4 ){
                            $('#errPassMsg').html("Invalid Password").css("color","red");
                        } else if(response.passFlag == 5 ){
                            $('#errPassMsg').html("Invalid Password").css("color","red");
                        } else if(response.passFlag == 6 ){
                            $('#errPassMsg').html("Invalid Password").css("color","red");
                        } else if(response.val == "" ){
                            $('#errPassMsg').html("Invalid Password");
                        } else {
                            $('#errCat').html("");
                            if(response.val== 1 ) {
                                $('#errPassMsg').html("Password Set!");
                            }
                        }
                },
                complete: function() {  
                },
                error: function() {
                }
           });
        }) */

$("#btnProfileSave").click(function(){
	/*if(!$('#imageUpload').value){
    	$('#imageUpload').val("<?php //echo $userProfile[0]['photo'];?>");
}*/

var profileData = {
		'profileFirstName'  : $('#txtFname').val(),
		'profileLastName'   : $('#txtLname').val(),
		'profileContact'    : $('#txtContact').val(),
		'profilePic'        : $('#imageUpload').val()
};

$('#passtab').click(function(){
	$("#errPassMsg1").html("");
	$("#oldPassword").val("");
	$("#newPassword").attr('disabled',true);
	$("#confirmPassword").attr('disabled',true);
	$("#btnSave").attr('disabled',true);
});

$( "#oldPassword" ).blur(function() {
    $.ajax({
        type: "POST",
        data: {'oldPassword':$("#oldPassword").val()},
        url: '/user/verifyOldPassword/'+$("#clientId").val(),
        dataType: 'json',
        beforeSend:function(){
            //alert($("#clientId").val());
        },
        success:function(response){
            //alert(response.flag);
            if(response.flag == 0){
                $("#errPassMsg1").html("Please Enter Valid Password !");
                $("#newPassword").attr('disabled',true);
                $("#confirmPassword").attr('disabled',true);
                $("#btnSave").attr('disabled',true);
            }else{
                $("#errPassMsg1").html("");
                $("#newPassword").attr('disabled',false);
                $("#confirmPassword").attr('disabled',false);
                $("#btnSave").attr('disabled',false);
            }
        }
    });
});

$( "#oldPassword" ).focusin(function() {
	$("#errPassMsg1").html("");
});
});

$("#btnSave").click(function(){    
    var passwordData = {
    	    'oldPassword'   : $('#oldPassword').val(),
    	    'newPassword'   : $('#newPassword').val(),
    	    'confirmPassword'   : $('#confirmPassword').val()
    		};
      /* if(String($('#newPassword').val()) == String($('#confirmPassword').val()){ */
            $.ajax({
           		type: "POST",
            	data: passwordData,
           	 	url: '/user/updateProfilePassword/'+$("#clientId").val(),
            	dataType: 'json',
            	beforeSend:function(){
                	//alert($("#clientId").val());
            	},
            	success:function(response){
                	//alert(response.flag);
                	if(response.flag == 1){
                    	window.location.reload();
                	}
                	/*
                	if(response.profileFlag == 1){
                    	$('#errContactMsg').html("");
                     	$('#errLnameMsg').html("");
                    	$('#errFnameMsg').html("Firstname cannot be blank").css("color","red");
                	} else if(response.profileFlag == 2){
                    	$('#errContactMsg').html("");
                     	$('#errLnameMsg').html("");
                    	$('#errFnameMsg').html("First name is invalid").css("color","red");
                	} else if(response.profileFlag == 3){
                    	$('#errContactMsg').html("");
                     	$('#errFnameMsg').html("");
                    	$('#errLnameMsg').html("Last name is invalid").css("color","red");
                	} else if(response.profileFlag == 4){
                    	$('#errLnameMsg').html("");
                    	$('#errContactMsg').html("");
                    	$('#errContactMsg').html("Contact is invalid").css("color","red");
                	} else if(response.val == ""){
                    	$('#errContactMsg').html("");
                     	$('#errLnameMsg').html("");
                    	$('#errFnameMsg').html("Server error").css("color","red");
                	} else if(response.val == 1){
                    	$('#errFnameMsg').html(" First Name Updated");
                    	$('#errLnameMsg').html(" Last Name Updated");
                    	$('#errContactMsg').html("");
                	} else {
                    	$('#errLnameMsg').html("");
                    	$('#errContactMsg').html("");
                    	$('#errFnameMsg').html("");
                	}
                */
            }
        });
      /* }else{
          $("#errPassMsg2").html("New Pasword and Confirm Password Doesn't Match ?")
      } */
    });

// $('#language').change(function(){
//     // alert($(this).val());
//     var lang = $(this).val();
// });

$('#btnThemeLang').click(function(){
    var langCode = $('#language').val();
    var Theme    = $('#color').val();
    var clientId = $('#client').val();
    if(Theme == "") {}
    else {
    	var lang = ((langCode == 'en')?'English':((langCode == 'fr')?'French':'Hindi'));
    	$.ajax({
        	type: "POST",
       		data: {profileLanguage:lang,profileTheme:Theme,clientid:clientId},
       	 	url: 'userSetting',
        	dataType: 'json',
        	success:function(response){
            	if(response.flag == 1) {
                	$('#langMsg').html("Changes Saved! ");
                	window.setTimeout(function() { $("#langMsg").css('visibility','hidden'); }, 2000);
               		// location.reload();
            	} else {
                	$('#langMsg').html("Error: Could not able to save the changes! ");
            	}
        	}
    	});
	}
});

$('.theme').click(function(){
    var theme = $(this).attr("value");
    if(theme === "Red"){
        $('#color').attr("value","1");
        $('link[href^="/css/themes"]').attr("href","/css/themes/red.css");
    }   
    else if(theme === "Green"){
        $('#color').attr("value","2");
        $('link[href^="/css/themes"]').attr("href","/css/themes/green.css");
    }
    else if(theme === "Yellow"){
        $('#color').attr("value","3");
        $('link[href^="/css/themes"]').attr("href","/css/themes/yellow.css");
    }
    else {
        $('#color').attr("value","0");
        $('link[href^="/css/themes"]').attr("href","/css/themes/blue.css");
    }
});
    
function addClassCurrent(element) {
    var el="#ico"+element;
    $(el).addClass("current");
}

function removeClassCurrent(element) {
    var el="#ico"+element;
    $(el).removeClass("current");
}

$('#footer').css("padding-top","30px");

$(document).on('change', '.btn-file :file', function() {
	var input = $(this);
    var numFiles = input.get(0).files ? input.get(0).files.length : 1;
	var label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
	$('#file-name').text(label);
});
</script>
<style>
.btn-file {
    position: relative;
    overflow: hidden;
}
.btn-file input[type=file] {
    position: absolute;
    top: 0;
    right: 0;
    min-width: 100%;
    min-height: 100%;
    font-size: 100px;
    text-align: right;
    filter: alpha(opacity=0);
    opacity: 0;
    outline: none;
    background: white;
    cursor: inherit;
    display: block;
}
    .profilePicSetting {
        height: 160px;
        width: 160px;
        border-radius: 80px;
    }
</style>