<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse"
				data-target=".navbar-collapse">
				<span class="icon-bar"></span> <span class="icon-bar"></span> <span
					class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="<?php echo $this->url('home') ?>">&nbsp;<?php echo $this->translate('TestCube') ?></a>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Login') ?></a></li>
				<li class=""><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('About Us') ?></a></li>
				<li class=""><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Service') ?></a></li>
				<li class=""><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Help') ?></a></li>
			</ul>
		</div>
		<!--/.nav-collapse -->
	</div>
</nav>