<?php
    echo $this->doctype();
    echo $this->headTitle($this->translate('TestCube Application'))->setSeparator(' - ')->setAutoEscape(false);
    echo $this->headMeta()
              ->appendName('viewport', 'width=device-width, initial-scale=1.0')
              ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
    $theme = 'blue';
    if(isset($themeselected)) :
        if($themeselected['themeselected'] == 1) :
            $theme = 'red';
        elseif ($themeselected['themeselected'] == 2) :
            $theme = 'green';
        elseif ($themeselected['themeselected'] == 3) :
            $theme = 'yellow';
       endif;
    endif;
    $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/themes/'.$theme.'.css')
        ->prependStylesheet($this->basePath() . '/css/dataTables.bootstrap.min.css')
        //->prependStylesheet($this->basePath() . '/css/certificate.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap_datetimepicker.css')
        ->prependStylesheet($this->basePath() . '/css/category.css')
        ->prependStylesheet($this->basePath() . '/css/style.css')
        //->prependStylesheet($this->basePath() . '/css/question.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ->prependStylesheet($this->basePath() . '/css/layout.css')
        ->prependStylesheet($this->basePath() . '/css/category.css'); 
    $this->headScript()
        //->prependFile($this->basePath() . '/js/certificate.js')
        ->prependFile($this->basePath() . '/js/dataTables.bootstrap.js')     
    	->prependFile($this->basePath() . '/js/dataTables.bootstrap.min.js')     
    	->prependFile($this->basePath() . '/js/bootstrap-datetimepicker.js')
    	->prependFile($this->basePath() . '/js/moment.min.js')
        ->prependFile($this->basePath() . '/js/category.js') 
        ->prependFile($this->basePath() . '/js/jquery.validate.js')
    	->prependFile($this->basePath() . '/js/script.js')
        //->prependFile($this->basePath() . '/js/question.js')
        //->prependFile($this->basePath() . '/js/result.js')
        //->prependFile($this->basePath() . '/js/test.js')
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')      
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',));