<?php echo $this->doctype();
use Zend\Session\Container;
$link = isset($this->layout()->modulenamespace)?$this->layout()->modulenamespace:"Error";
?>
<html lang="en">
	<head>
    	<meta charset="utf-8">
		<?php echo $this->partial('layout/head', array('doctype' => $this->doctype()));?>
<?php if($link == "Application" || $link == "Error" || $link == "NotLoggedIn") :?>
	<?php  echo $this->headLink();?>
    <?php  echo $this->headScript();?>
	</head>
    <body>
    <?php echo $this->partial('layout/header-first');?>
    	<div class="container"> 
	  		<div id="content">
	  			<?php echo $this->content; ?>	  			
    		</div>
           	<hr>
           	<?php echo $this->partial('layout/footer');?>
        </div>
    </body>
</html>
<?php elseif($link == "Student") :?>
	<?php echo $this->headLink()
                    ->prependStylesheet($this->basePath() . '/css/countdownTimer.css')
				    ->prependStylesheet($this->basePath() . '/css/student.css');
          echo $this->headScript()
                    ->prependFile($this->basePath() . '/js/student.js')
                    ->appendFile($this->basePath() . '/js/countdownTimer.js');
    ?>
	</head>
    <body>
    	<?php echo $this->partial('layout/header-second');?>
        <div class="container">
        	<div id="content">
	  			<?php echo $this->content; ?>
    		</div>
            <hr>
           <?php echo $this->partial('layout/footer');?>
        </div>
    </body>
</html>
<?php 
    else:
    switch ($link){
	   case 'Category':
	       $pageinfo  = "Categories for the Test";
	       $pageicon  = "glyphicon-th";
	       break;
	   case 'Dashboard':
		   $pageinfo  = "information about all modules at one place";
		   $pageicon = "glyphicon-inbox";
		   break;
	   case 'Question':
		   $pageinfo  = "Question Bank for the Test";
		   $pageicon = "glyphicon-list-alt";
		   break;
	   case 'Test':
	   	   $pageinfo  = "All Tests in one place";
	   	   $pageicon = "glyphicon-file";
	   	   break;
	   case 'Certificate':
	       $pageinfo  = "Certificates generated for test takers";
	       $pageicon = "glyphicon-certificate";
	       break;
	   case 'Result':
	       $pageinfo  = "Test Result";
	       $pageicon = "glyphicon-check";
	       break;
	   case 'User':
	       $pageinfo  = "User Information at one place";
	       $pageicon = "glyphicon-user";
	       break;
	   default:
		   $pageinfo  = "TestCube";
		   $pageicon = "glyphicon-inbox";
    }
    $userSession = new Container('users');
    $usrname =  isset($userSession->username)?$userSession->username:'Guest';	
	echo $this->headLink()
		      ->prependStylesheet($this->basePath() . '/css/themes/blue.css');
	echo $this->headScript()
              ->prependFile($this->basePath() . '/js/script.js')
		      ->appendFile($this->basePath() . '/js/ticker.js');
?>
	</head>
	<body>
		<?php echo $this->partial('layout/header-third', array('username' => $usrname));?>
		<div id="dash-content" class="container">
			<?php echo $this->partial('layout/dash-menu', array('link' => $link, 'countData' => $this->countData));?>
        		<div id="dash-right-content">
        			<div id="content-border" class="blue-background"></div>
            		<div id="content-header">
            			<div id="text"><?php echo $pageinfo ?></div>
            			<div id="heading">
            				<span class="icon glyphicon <?php echo $pageicon;?> margin-right5"></span>
            				<span><?php echo $link?></span>
            			</div>
            		</div> <!-- end of content header-->
            		<div id="header-arrow" ></div>
            		<div class="content">
                		<?php echo $this->content; ?>
         			</div>         
       			</div>
       	</div>
       	<?php echo $this->partial('layout/footer');?>
	</body>
</html>                  
<?php endif;?>