<div id="loginForm"></div>
<!-- Register Popup Content -->
<div id="popupContent">
	<!-- start of lightbox -->
	<div id="light" class="light-box">
		<div class="light-box-banner">
			<span class="float-left margin-left25">RegisterNewUser</span> <a
				href="/">
				<div id="closePopup" class="close-btn float-right"
					data-dismiss="popupContent"></div>
			</a>
		</div>
		<!-- end of white-content-banner -->

		<div class="light-box-content">
			<form id="frmRegister" name="frmRegister"></form>
		</div>
		<!-- end of white-content-content-->
	</div>
	<!-- end of light-box  -->
	<div id="fade" class="black_overlay"></div>
</div>
<!-- end of popup-content -->

<script>
$(document).ready(function(){
	$.ajax({
		type:'get',	
		url:'/user/login<?php if(isset($id)){echo "/?id=".$id;} if(isset($statusmsg)){echo "/?statusmsg=".$statusmsg;} ?>',
		dataType:'html',
		data:'',
		success:function(data){
				$('#loginForm').html(data);
		}
	});
});
</script>